import type { Agent } from './types'

export const AGENTS: Agent[] = [
  // ── Chat rápido & atendimento ─────────────────────────────────────────────
  {
    id: 'mare',
    name: 'Relay',
    role: 'Atendimento e triagem express',
    category: 'chat',
    backend: 'deepseek',
    modelAlias: 'angra.ma1',
    tier: 'subagente',
    servesPrincipal: 'caio',
    modelTier: 'sonnet',
    systemPrompt: 'Você é Relay, agente de atendimento ultra-rápido da Strategy Partners.',
    dot: '#38BDF8',
    barColor: '#0EA5E9',
    active: false,
    avatar: '/agentes/agente1.webp',
    specs: [
      'Roteamento de tickets em tempo real com triagem por prioridade',
      'Adaptação de tom automática — formal, empático ou técnico por contexto',
      'Bridging multicanal com preservação de histórico completo',
      'Protocolo de escalada para agentes especialistas da frota',
    ],
  },
  {
    id: 'brisa',
    name: 'Consul',
    role: 'Assistente consultivo geral',
    category: 'chat',
    backend: 'deepseek',
    modelAlias: 'angra.br1',
    tier: 'subagente',
    servesPrincipal: 'caio',
    modelTier: 'sonnet',
    systemPrompt: 'Você é Consul, assistente conversacional da Strategy Partners.',
    dot: '#7DD3FC',
    barColor: '#38BDF8',
    active: false,
    avatar: '/agentes/agente2.webp',
    specs: [
      'Diálogo aberto com janela de contexto contínua entre sessões',
      'Registro adaptativo — de reunião executiva a conversa informal',
      'Síntese de bases de conhecimento conectadas à frota',
      'Fluência bilíngue PT/EN com paridade de nível profissional',
    ],
  },
  {
    id: 'eco',
    name: 'Brief',
    role: 'Triagem e sumarização executiva',
    category: 'chat',
    backend: 'deepseek',
    modelAlias: 'angra.ec1',
    tier: 'subagente',
    servesPrincipal: 'caio',
    modelTier: 'sonnet',
    systemPrompt: 'Você é Brief, especialista em triagem e sumarização da Strategy Partners.',
    dot: '#BAE6FD',
    barColor: '#7DD3FC',
    active: false,
    avatar: '/agentes/agente3.webp',
    specs: [
      'Extração de pontos-chave em documentos de até 200 páginas',
      'Sumarização hierárquica com score de acionabilidade',
      'Deduplicação multi-fonte antes da consolidação final',
      'Saída estruturada compatível com CRM, ERP e BI',
    ],
  },

  // ── Vendas ────────────────────────────────────────────────────────────────
  {
    id: 'corsario',
    name: 'Apex',
    role: 'SDR — prospecção e qualificação',
    category: 'vendas',
    backend: 'deepseek',
    modelAlias: 'angra.cs1',
    tier: 'subagente',
    servesPrincipal: 'novae',
    modelTier: 'sonnet',
    systemPrompt: 'Você é Apex, SDR especializado da Strategy Partners.',
    dot: '#F97316',
    barColor: '#EA580C',
    active: false,
    avatar: '/agentes/agente4.webp',
    specs: [
      'Scoring de ICP com dados firmográficos e comportamentais',
      'Cadências de outreach personalizadas com variações A/B',
      'Extração de dores latentes em comunicações de prospects',
      'Qualificação nativa nos frameworks BANT e MEDDIC',
    ],
  },
  {
    id: 'negociador',
    name: 'Titan',
    role: 'Objeções, negociação e fechamento',
    category: 'vendas',
    backend: 'deepseek',
    modelAlias: 'angra.ng1',
    tier: 'subagente',
    servesPrincipal: 'novae',
    modelTier: 'sonnet',
    systemPrompt: 'Você é Titan, especialista em fechamento de vendas da Strategy Partners.',
    dot: '#FB923C',
    barColor: '#F97316',
    active: false,
    avatar: '/agentes/agente5.webp',
    specs: [
      'Mapa de objeções em tempo real com banco de contra-argumentos',
      'Estratégia de concessão baseada em playbooks de negociação',
      'Análise de padrões win/loss com 18+ variáveis históricas',
      'Detecção de gatilhos de fechamento com calibração de urgência',
    ],
  },
  {
    id: 'vitrine',
    name: 'Pitch',
    role: 'Copywriting e proposta comercial',
    category: 'vendas',
    backend: 'deepseek',
    modelAlias: 'angra.vt1',
    tier: 'subagente',
    servesPrincipal: 'novae',
    modelTier: 'sonnet',
    systemPrompt: 'Você é Pitch, especialista em copywriting da Strategy Partners.',
    dot: '#FDBA74',
    barColor: '#FB923C',
    active: false,
    avatar: '/agentes/agente6.webp',
    specs: [
      'Copy orientado a persona com ajuste de tom e nível de leitura',
      'Templates de proposta calibrados para 6 verticais de mercado',
      'Verificação de conformidade com voz de marca antes da entrega',
      'Geração de variações de headline com predição de CTR',
    ],
  },

  // ── Segurança ─────────────────────────────────────────────────────────────
  {
    id: 'sentinela',
    name: 'Aegis',
    role: 'Threat intelligence e análise de segurança',
    category: 'segurança',
    backend: 'deepseek',
    modelAlias: 'angra.sn1',
    tier: 'subagente',
    servesPrincipal: 'caio',
    modelTier: 'sonnet',
    systemPrompt: 'Você é Aegis, especialista em threat intelligence da Strategy Partners.',
    dot: '#EF4444',
    barColor: '#DC2626',
    active: false,
    avatar: '/agentes/agente7.webp',
    specs: [
      'Reconhecimento de padrões de ameaça em streams de log em tempo real',
      'Mapeamento de CVEs contra infraestrutura ativa do cliente',
      'Análise de kill-chain com alinhamento ao framework MITRE ATT&CK',
      'Roteamento de escalada por severidade e valor do ativo comprometido',
    ],
  },
  {
    id: 'guardiao',
    name: 'Lex',
    role: 'Compliance, LGPD e regulatório',
    category: 'segurança',
    backend: 'deepseek',
    modelAlias: 'angra.gd1',
    tier: 'subagente',
    servesPrincipal: 'caio',
    modelTier: 'sonnet',
    systemPrompt: 'Você é Lex, especialista em compliance e LGPD da Strategy Partners.',
    dot: '#F87171',
    barColor: '#EF4444',
    active: false,
    avatar: '/agentes/agente8.webp',
    specs: [
      'Análise de lacunas LGPD artigo por artigo contra processos vigentes',
      'Mapeamento de fluxo de dados com identificação automática de PII',
      'Elaboração de DPIA com matriz de risco e plano de mitigação',
      'Relatórios de conformidade automatizados para revisão do DPO',
    ],
  },
  {
    id: 'vigia',
    name: 'Sigma',
    role: 'Detecção de anomalias e intrusões',
    category: 'segurança',
    backend: 'deepseek',
    modelAlias: 'angra.vg1',
    tier: 'subagente',
    servesPrincipal: 'caio',
    modelTier: 'sonnet',
    systemPrompt: 'Você é Sigma, especialista em detecção de anomalias da Strategy Partners.',
    dot: '#FCA5A5',
    barColor: '#F87171',
    active: false,
    avatar: '/agentes/agente9.webp',
    specs: [
      'Modelagem de baseline comportamental com detecção de deriva',
      'Correlação cross-sistema para padrões de movimentação lateral',
      'Reconhecimento de assinaturas de ataques low-and-slow',
      'Redução de alert fatigue via deduplicação inteligente',
    ],
  },

  // ── Financeiro ────────────────────────────────────────────────────────────
  {
    id: 'asten',
    name: 'ASTEN',
    role: 'Finanças corporativas e mercado de capitais',
    category: 'financeiro',
    backend: 'deepseek',
    modelAlias: 'angra.ts1',
    tier: 'principal',
    modelTier: 'fable',
    systemPrompt: 'Você é ASTEN, especialista em finanças corporativas e mercado de capitais da Strategy Partners.',
    dot: '#22C55E',
    barColor: '#16A34A',
    active: true,
    avatar: '/agentes/agente10.webp',
    specs: [
      'Modelagem DCF, LBO e transações comparáveis com sensitividade',
      'Análise de cenários com simulação Monte Carlo integrada',
      'Diagnóstico de ciclo de capital de giro e alavancagem operacional',
      'Narrativa financeira executiva pronta para board e investidores',
    ],
  },
  {
    id: 'contabil',
    name: 'Ledger',
    role: 'Conciliação contábil e BPO financeiro',
    category: 'financeiro',
    backend: 'deepseek',
    modelAlias: 'angra.cb1',
    tier: 'subagente',
    servesPrincipal: 'asten',
    modelTier: 'sonnet',
    systemPrompt: 'Você é Ledger, especialista em conciliação contábil da Strategy Partners.',
    dot: '#4ADE80',
    barColor: '#22C55E',
    active: false,
    avatar: '/agentes/agente11.webp',
    specs: [
      'Conciliação tripla automatizada — banco, ERP e razão contábil',
      'Sinalização de exceções com classificação de causa-raiz',
      'Aceleração de fechamento mensal com comentário de variações',
      'Saída compatível com SAP, TOTVS, Omie e sistemas legados',
    ],
  },
  {
    id: 'auditor',
    name: 'Diligence',
    role: 'Due diligence e auditoria financeira',
    category: 'financeiro',
    backend: 'deepseek',
    modelAlias: 'angra.ad1',
    tier: 'subagente',
    servesPrincipal: 'merko',
    modelTier: 'sonnet',
    systemPrompt: 'Você é Diligence, especialista em due diligence da Strategy Partners.',
    dot: '#86EFAC',
    barColor: '#4ADE80',
    active: false,
    avatar: '/agentes/agente12.webp',
    specs: [
      'Detecção de red flags em 40+ categorias de risco financeiro',
      'Mapeamento de exposições off-balance-sheet e contingências',
      'Análise de qualidade de earnings com modelagem de ajustes',
      'Sumário executivo com priorização de deal-breakers',
    ],
  },

  // ── Programação ───────────────────────────────────────────────────────────
  {
    id: 'forja',
    name: 'Forge',
    role: 'Engenharia de software e geração de código',
    category: 'programação',
    backend: 'deepseek',
    modelAlias: 'angra.fj1',
    tier: 'subagente',
    servesPrincipal: 'tycen',
    modelTier: 'sonnet',
    systemPrompt: 'Você é Forge, especialista em geração de código da Strategy Partners.',
    dot: '#A855F7',
    barColor: '#9333EA',
    active: false,
    avatar: '/agentes/agente13.webp',
    specs: [
      'Geração multi-linguagem — JS, Python, Go, Rust, SQL, TypeScript',
      'Refatoração orientada a contexto com análise de grafo de dependências',
      'Geração automática de testes com cobertura de edge cases',
      'Documentação inline e scoring de complexidade ciclomática',
    ],
  },
  {
    id: 'revisor',
    name: 'Codex',
    role: 'Code review, refatoração e qualidade',
    category: 'programação',
    backend: 'deepseek',
    modelAlias: 'angra.rv1',
    tier: 'subagente',
    servesPrincipal: 'tycen',
    modelTier: 'sonnet',
    systemPrompt: 'Você é Codex, especialista em code review da Strategy Partners.',
    dot: '#C084FC',
    barColor: '#A855F7',
    active: false,
    avatar: '/agentes/agente14.webp',
    specs: [
      'Varredura de padrões OWASP Top 10 com sugestões de correção',
      'Detecção de anti-patterns de performance com benchmarks',
      'Scoring de clean code alinhado ao style guide do projeto',
      'Quantificação de débito técnico com roadmap de remediação',
    ],
  },
  {
    id: 'arquiteto',
    name: 'Blueprint',
    role: 'Arquitetura de sistemas e design técnico',
    category: 'programação',
    backend: 'deepseek',
    modelAlias: 'angra.aq1',
    tier: 'subagente',
    servesPrincipal: 'tycen',
    modelTier: 'sonnet',
    systemPrompt: 'Você é Blueprint, especialista em design de sistemas da Strategy Partners.',
    dot: '#E879F9',
    barColor: '#D946EF',
    active: false,
    avatar: '/agentes/agente15.webp',
    specs: [
      'Modelagem Domain-Driven Design com bounded contexts explícitos',
      'Geração de contratos de API — OpenAPI, gRPC e AsyncAPI',
      'Análise de escalabilidade com projeção de gargalos futuros',
      'Elaboração de ADRs (Architecture Decision Records) rastreáveis',
    ],
  },
  {
    id: 'estaleiro',
    name: 'Pipeline',
    role: 'DevOps, IaC e infraestrutura cloud',
    category: 'programação',
    backend: 'deepseek',
    modelAlias: 'angra.et1',
    tier: 'subagente',
    servesPrincipal: 'tycen',
    modelTier: 'sonnet',
    systemPrompt: 'Você é Pipeline, especialista em DevOps da Strategy Partners.',
    dot: '#F0ABFC',
    barColor: '#E879F9',
    active: false,
    avatar: '/agentes/agente16.webp',
    specs: [
      'Geração de Infrastructure-as-Code — Terraform e Pulumi',
      'Design de pipelines CI/CD com quality gates automatizados',
      'Specs de orquestração de containers — Kubernetes e Compose',
      'Blueprints de arquitetura cloud com otimização de custo',
    ],
  },

  // ── Conhecimento & operação ───────────────────────────────────────────────
  {
    id: 'jurista',
    name: 'Counsel',
    role: 'Análise jurídica e revisão de contratos',
    category: 'conhecimento',
    backend: 'deepseek',
    modelAlias: 'angra.jr1',
    tier: 'subagente',
    servesPrincipal: 'merko',
    modelTier: 'sonnet',
    systemPrompt: 'Você é Counsel, especialista em análise de contratos da Strategy Partners.',
    dot: '#0B3A78',
    barColor: '#1E40AF',
    active: false,
    avatar: '/agentes/agente17.webp',
    specs: [
      'Score de risco cláusula a cláusula em 18 tipos de contrato',
      'Flagging de termos não-padrão versus precedente de mercado',
      'Extração de linha do tempo de obrigações com mapa de alertas',
      'Geração de redline com posição de negociação anotada',
    ],
  },
  {
    id: 'pesquisador',
    name: 'Beacon',
    role: 'Research profundo e inteligência de mercado',
    category: 'conhecimento',
    backend: 'deepseek',
    modelAlias: 'angra.ps1',
    tier: 'subagente',
    servesPrincipal: 'merko',
    modelTier: 'sonnet',
    systemPrompt: 'Você é Beacon, especialista em research da Strategy Partners.',
    dot: '#1D4ED8',
    barColor: '#1E3A8A',
    active: false,
    avatar: '/agentes/agente18.webp',
    specs: [
      'Síntese multi-fonte com pontuação de confiança por claim',
      'Identificação de lacunas de pesquisa com fontes sugeridas',
      'Saída estruturada alinhada a formatos consultivos entregáveis',
      'Cross-referência entre bases internas e fontes abertas verificadas',
    ],
  },
  {
    id: 'interprete',
    name: 'Lingua',
    role: 'Tradução e localização multilíngue',
    category: 'conhecimento',
    backend: 'deepseek',
    modelAlias: 'angra.ip1',
    tier: 'subagente',
    servesPrincipal: 'caio',
    modelTier: 'sonnet',
    systemPrompt: 'Você é Lingua, especialista em tradução da Strategy Partners.',
    dot: '#2563EB',
    barColor: '#1D4ED8',
    active: false,
    avatar: '/agentes/agente19.webp',
    specs: [
      'Tradução técnica e jurídica em 8 domínios especializados',
      'Consistência terminológica via glossário controlado por projeto',
      'Adaptação cultural além da tradução literal — idiomas e contextos',
      'Verificação de qualidade via back-translation embutida',
    ],
  },
  {
    id: 'tycen',
    name: 'TYCEN',
    role: 'Transformação, execução e PMO',
    category: 'conhecimento',
    backend: 'deepseek',
    modelAlias: 'angra.an1',
    tier: 'principal',
    modelTier: 'fable',
    systemPrompt: 'Você é TYCEN, especialista em transformação, execução, PMO e turnaround operacional da Strategy Partners.',
    dot: '#3B82F6',
    barColor: '#2563EB',
    active: true,
    avatar: '/agentes/agente20.webp',
    specs: [
      'Plano de 100 dias com marcos verificáveis e donos nomeados',
      'PMO de integração pós-deal (PMI) — governança, cadência e RAID log',
      'Turnaround operacional/financeiro com quick wins e captura de sinergias',
      'KPIs de execução e dashboards de acompanhamento por milestone',
    ],
  },
  {
    id: 'redator',
    name: 'Chronicle',
    role: 'Produção de conteúdo e marketing editorial',
    category: 'conhecimento',
    backend: 'deepseek',
    modelAlias: 'angra.rd1',
    tier: 'subagente',
    servesPrincipal: 'novae',
    modelTier: 'sonnet',
    systemPrompt: 'Você é Chronicle, especialista em conteúdo da Strategy Partners.',
    dot: '#60A5FA',
    barColor: '#3B82F6',
    active: false,
    avatar: '/agentes/agente21.webp',
    specs: [
      'Produção de long-form e micro-copy em 8 formatos de conteúdo',
      'Estrutura SEO-otimizada com integração de palavras-chave',
      'Calibração de tom de marca com scoring de consistência',
      'Modelo de predição de alcance orgânico por tipo de conteúdo',
    ],
  },
  {
    id: 'novae',
    name: 'NOVAE',
    role: 'Novos negócios e crescimento',
    category: 'conhecimento',
    backend: 'deepseek',
    modelAlias: 'angra.eg1',
    tier: 'principal',
    modelTier: 'fable',
    systemPrompt: 'Você é NOVAE, especialista em novos negócios, growth e validação de MVP da Strategy Partners.',
    dot: '#93C5FD',
    barColor: '#60A5FA',
    active: true,
    avatar: '/agentes/agente22.webp',
    specs: [
      'Planejamento de cenários com desfechos ponderados por probabilidade',
      'Síntese de inteligência competitiva a partir de sinais de mercado',
      'Mapeamento de opções estratégicas com modelagem de recursos',
      'Design de cascata OKR — da visão ao nível de equipe',
    ],
  },
  {
    id: 'caio',
    name: 'CAIO',
    role: 'Orquestração e síntese multi-agente',
    category: 'conhecimento',
    backend: 'deepseek',
    modelAlias: 'angra.mt1',
    tier: 'principal',
    modelTier: 'opus',
    systemPrompt: 'Você é CAIO, orquestrador e sintetizador multi-agente da Strategy Partners.',
    dot: '#BFDBFE',
    barColor: '#93C5FD',
    active: true,
    avatar: '/agentes/agente23.webp',
    specs: [
      'Design de workflows multi-agente com resolução de dependências',
      'Roteamento dinâmico de tarefas por carga e especialização',
      'Agregação por consenso de outputs paralelos da frota',
      'Monitoramento de execução com lógica de retry e fallback',
    ],
  },
  {
    id: 'curador',
    name: 'Director',
    role: 'Governança e atualização da frota',
    category: 'conhecimento',
    backend: 'deepseek',
    modelAlias: 'angra.cr1',
    tier: 'subagente',
    servesPrincipal: 'caio',
    modelTier: 'sonnet',
    systemPrompt: 'Você é Director, meta-modelo da frota da Strategy Partners.',
    dot: '#DBEAFE',
    barColor: '#BFDBFE',
    active: false,
    avatar: '/agentes/agente24.webp',
    specs: [
      'Monitoramento de saúde da frota em todos os 27 agentes',
      'Detecção de prompt drift e alertas de regressão de performance',
      'Manutenção de documentação de capacidades e changelog',
      'Protocolo de onboarding e certificação de novos agentes',
    ],
  },
  {
    id: 'farol',
    name: 'Router',
    role: 'Roteamento inteligente de intenção',
    category: 'conhecimento',
    backend: 'deepseek',
    modelAlias: 'angra.fl1',
    tier: 'subagente',
    servesPrincipal: 'caio',
    modelTier: 'sonnet',
    systemPrompt: 'Você é Router, roteador de intenção da Strategy Partners.',
    dot: '#EFF6FF',
    barColor: '#DBEAFE',
    active: false,
    avatar: '/agentes/agente25.webp',
    specs: [
      'Classificação de intenção em 200+ categorias temáticas',
      'Roteamento por confiança com limiar de escalada configurável',
      'Preservação de contexto completo nas transições entre agentes',
      'Loop de feedback para melhoria contínua de precisão de roteamento',
    ],
  },
  {
    id: 'ancora',
    name: 'Anchor',
    role: 'Embeddings, indexação e retrieval RAG',
    category: 'conhecimento',
    backend: 'deepseek',
    modelAlias: 'angra.nc1',
    tier: 'subagente',
    servesPrincipal: 'caio',
    modelTier: 'sonnet',
    systemPrompt: 'Você é Anchor, responsável por embeddings e RAG da Strategy Partners.',
    dot: '#F0F9FF',
    barColor: '#E0F2FE',
    active: false,
    avatar: '/agentes/agente26.webp',
    specs: [
      'Geração de embeddings com fine-tuning específico por domínio',
      'Busca híbrida BM25 + semântica com re-ranking por relevância',
      'Estruturação de bases de conhecimento com taxonomia controlada',
      'Scoring de qualidade de retrieval com redução de alucinação',
    ],
  },

  // ── M&A & Assessoria ─────────────────────────────────────────────────────────
  {
    id: 'merko',
    name: 'MERKO',
    role: 'M&A Advisor — fusões, aquisições e reestruturação',
    category: 'conhecimento',
    backend: 'deepseek',
    modelAlias: 'angra.ob1',
    tier: 'principal',
    modelTier: 'fable',
    systemPrompt: 'Você é MERKO, advisor de M&A da Strategy Partners — fusões, aquisições, valuation e due diligence buy-side e sell-side.',
    dot: '#0B2A4A',
    barColor: '#1E3A5F',
    active: true,
    avatar: '/agentes/agente27.webp',
    specs: [
      'Estruturação de deals buy-side e sell-side com minutas de term sheet',
      'Valuation empresarial — DCF, EV/EBITDA e transações precedentes',
      'Planejamento de integração com mapeamento de sinergias',
      'Análise de ativos distressed com roadmap de turnaround',
    ],
  },
]

export const AGENTS_BY_CATEGORY = AGENTS.reduce(
  (acc, agent) => {
    if (!acc[agent.category]) acc[agent.category] = []
    acc[agent.category].push(agent)
    return acc
  },
  {} as Record<string, Agent[]>,
)

export const CHAT_AGENTS = AGENTS.filter(a => a.category === 'chat')
